In [422]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/heart-disease-uci/heart.csv

In [423]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [424]:
df = pd.read_csv('/kaggle/input/heart-disease-uci/heart.csv') #df stands for dataframe

In [425]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [426]:
df.shape

(303, 14)

***Exploratory data analysis***

In [427]:
df = df[df['thal'] != 0]

In [433]:
df['age'].value_counts()

AttributeError: 'Series' object has no attribute 'sort'

In [429]:
df = df[df['age'] != 29]

In [430]:
df['thal'] = df['thal'].replace(1, 'fixed defect')
df['thal'] = df['thal'].replace(2, 'normal')
df['thal'] = df['thal'].replace(3, 'reversable defect')
df['cp'] = df['cp'].replace(0, 'asymptomatic')
df['cp'] = df['cp'].replace(1, 'atypical angina')
df['cp'] = df['cp'].replace(2, 'non-anginal pain')
df['cp'] = df['cp'].replace(3, 'typical angina')
df['restecg'] = df['restecg'].replace(0, 'ventricular hypertrophy')
df['restecg'] = df['restecg'].replace(1, 'normal')
df['restecg'] = df['restecg'].replace(2, 'ST-T wave abnormality')
df['slope'] = df['slope'].replace(0, 'downsloping')
df['slope'] = df['slope'].replace(1, 'flat')
df['slope'] = df['slope'].replace(2, 'upsloping')
df['target'] = df['target'].replace(0, 'disease')
df['target'] = df['target'].replace(1, 'no disease')

In [431]:
temp = pd.get_dummies(df[['cp', 'restecg', 'target', 'slope', 'thal']])

In [432]:
df = df.join(temp, how='left')
df = df.drop(['cp'], axis=1)
df = df.drop(['restecg'], axis=1)
df = df.drop(['target'], axis=1)
df = df.drop(['slope'], axis=1)
df = df.drop(['thal'], axis=1)
df

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,ca,cp_asymptomatic,...,restecg_normal,restecg_ventricular hypertrophy,target_disease,target_no disease,slope_downsloping,slope_flat,slope_upsloping,thal_fixed defect,thal_normal,thal_reversable defect
0,63,1,145,233,1,150,0,2.3,0,0,...,0,1,0,1,1,0,0,1,0,0
1,37,1,130,250,0,187,0,3.5,0,0,...,1,0,0,1,1,0,0,0,1,0
2,41,0,130,204,0,172,0,1.4,0,0,...,0,1,0,1,0,0,1,0,1,0
3,56,1,120,236,0,178,0,0.8,0,0,...,1,0,0,1,0,0,1,0,1,0
4,57,0,120,354,0,163,1,0.6,0,1,...,1,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,140,241,0,123,1,0.2,0,1,...,1,0,1,0,0,1,0,0,0,1
299,45,1,110,264,0,132,0,1.2,0,0,...,1,0,1,0,0,1,0,0,0,1
300,68,1,144,193,1,141,0,3.4,2,1,...,1,0,1,0,0,1,0,0,0,1
301,57,1,130,131,0,115,1,1.2,1,1,...,1,0,1,0,0,1,0,0,0,1
302,57,0,130,236,0,174,0,0.0,1,0,...,0,1,1,0,0,1,0,0,1,0